### ISSUE TITLE
[BUG] Fatal error:  Uncaught TypeError: Argument 1 passed to XMLUrlsSerializer::serialize() must be an instance of Urls, bool given

### ISSUE THREAD

**Issue by wiltonsr** [OCSInventory-NG/OCSInventory-ocsreports#1365]
**OCS Inventory version**
Version : 2.9 Docker

**Describe the bug**
After some time running a container when trying to login in web console the error is thrown

**Log file (optional)**

```log
ocsreports.0.5vme83ir2l7o@cctdcapllx0691    | [Mon Apr 11 14:54:37 2022] [error] [pid 54] sapi_apache2.c(349): [X-Real-Ip 10.204.116.166] [client 10.0.29.188:37284, 10.204.116.166, 10.222.157.127] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to XMLUrlsSerializer::serialize() must be an instance of Urls, bool given, called in /usr/share/ocsinventory-reports/ocsreports/require/config/include.php on line 57 and defined in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLUrlsSerializer.php:29\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/require/config/include.php(57): XMLUrlsSerializer->serialize(false)\n#1 /usr/share/ocsinventory-reports/ocsreports/require/config/include.php(46): migrate_urls_2_2(false)\n#2 /usr/share/ocsinventory-reports/ocsreports/backend/identity/methode/local.php(50): migrate_config_2_2()\n#3 /usr/share/ocsinventory-reports/ocsreports/backend/identity/identity.php(33): require_once('/usr/share/ocsi...')\n#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(328): require_once('/usr/share/ocsi...')\n#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('/usr/share/ocsi...')\n#6 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/require/config/XMLUrlsSerializer.php on line 29
ocsreports.0.5vme83ir2l7o@cctdcapllx0691    | 10.0.29.188, 10.204.116.166, 10.222.157.127 - - [11/Apr/2022:14:54:37 -0300] "GET /ocsreports/ HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29"
```

**Comment by gillesdubois** [comment]
Hi,

This issue is a bit old and OCS docker entrypoint had a lot of modifications since. I'll close this issue.
Feel free to reopen it in the docker repository.

Regards,
Gilles.
