### ISSUE TITLE
[BUG] LDAP filters missing

### ISSUE THREAD

**Issue by MichaIJarosz** [OCSInventory-NG/OCSInventory-ocsreports#1415]
**OCS Inventory version**
Version : 2.10 (screenshot 3)

**Describe the bug**
It is impossible to configure groups for LDAP users.  This is not a problem with wrong credentials, because if I set "CONEX_LDAP_CHECK_DEFAULT_ROLE" the login works.

**To Reproduce**
1. Go to "System Configuration"
2. Choose "LDAP configuration"
3. Scroll down to the end of site. There is no way to configure group options for LDAP users (screenshot 1)
4. Set "AUTH_TYPE" in var.php.
5. Restart apache2.
6. Try to login.
7. You see the errors in apache2 logs (added at the bottom) and error message in the browser (screenshot 2)

**Expected behavior**
Groups for LDAP users working correctly :)

**Screenshots**

1. 
![Lack of parameters](https://user-images.githubusercontent.com/54057029/185713717-7962b697-af81-476f-8980-4dea43a4599e.png)

2.
![Error after trying to login](https://user-images.githubusercontent.com/54057029/185713579-1afbc8e4-868c-46d2-a686-f40efcf8de4a.png)

3. 
![obraz](https://user-images.githubusercontent.com/54057029/185714516-7ffa2810-b9ab-4e47-b422-888c1ca8f260.png)

**Log file (optional)**
Logs from apache2:
```log
[Fri Aug 19 23:39:49.526151 2022] [php:warn] [pid 6165] [client 172.XX.XX.XX:63282] PHP Warning:  Undefined variable $filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 99, referer: https://inventory.domain.XYZ/index.php
[Fri Aug 19 23:39:49.526199 2022] [php:warn] [pid 6165] [client 172.XX.XX.XX:63282] PHP Warning:  Undefined variable $filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 99, referer: https://inventory.domain.XYZ/index.php
[Fri Aug 19 23:39:53.939914 2022] [php:warn] [pid 6168] [client 172.XX.XX.XX:63286] PHP Warning:  Undefined variable $filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 99, referer: https://inventory.domain.XYZ/index.php
[Fri Aug 19 23:39:53.939959 2022] [php:warn] [pid 6168] [client 172.XX.XX.XX:63286] PHP Warning:  Undefined variable $filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 99, referer: https://inventory.domain.XYZ/index.php
[Fri Aug 19 23:39:54.089171 2022] [php:warn] [pid 6168] [client 172.XX.XX.XX:63286] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 125, referer: https://inventory.domain.XYZ/index.php

[Fri Aug 19 23:43:47.071940 2022] [php:warn] [pid 6231] [client 172.XX.XX.XX:63320] PHP Warning:  Undefined variable $ldap_filters in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 588, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
[Fri Aug 19 23:43:47.072025 2022] [php:warn] [pid 6231] [client 172.XX.XX.XX:63320] PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 1059, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
```

**Comment by Lea9250** [comment]
Hi @MichaIJarosz,

There is indeed an issue here with the number of LDAP filters being displayed, you should be able to see 2 ldap filters (referring to CONEX_LDAP_NB_FILTERS option). We will be working on fixing this.
In the meantime, if you set the CONEX_LDAP_NB_FILTERS to more than 2 and update the configuration, do new CONEX_LDAP_FILTER and CONEX_LDAP_FILTER_ROLE fields appear on the refreshed page ? If so, you can use these to set up your LDAP groups.
I'll update this issue when a fix is available.

Regards,
Léa

**Comment by MichaIJarosz** [comment]
HI @Lea9250,
Yes, I can set CONEX_LDAP_NB_FILTERS to 3 or 4, and appropriate fields will appear (for 3rd and 4th filter) :
![obraz](https://user-images.githubusercontent.com/54057029/186106625-c5b42321-30da-406e-9d2e-67be30805e1e.png)

However, even when I configure them, I can't log in:
```log
[Tue Aug 23 09:58:11.290042 2022] [php:warn] [pid 48464] [client 172.XX.XX.XX:57423] PHP Warning:  Undefined variable $ldap_filters in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 588, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
[Tue Aug 23 09:58:11.290557 2022] [php:warn] [pid 48464] [client 172.XX.XX.XX:57423] PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 1059, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
[Tue Aug 23 09:58:17.342508 2022] [php:warn] [pid 48439] [client 172.XX.XX.XX:57432] PHP Warning:  Undefined variable $ldap_filters in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 588, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
[Tue Aug 23 09:58:17.342560 2022] [php:warn] [pid 48439] [client 172.XX.XX.XX:57432] PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/ocsinventory-reports/ocsreports/require/function_config_generale.php on line 440, referer: https://inventory.domain.XYZ/index.php?function=admin_conf
[Tue Aug 23 10:01:01.638218 2022] [php:warn] [pid 48497] [client 172.XX.XX.XX:57477] PHP Warning:  ldap_search(): Search: Bad search filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 83, referer: https://inventory.domain.XYZ/index.php
[Tue Aug 23 10:01:01.638348 2022] [php:error] [pid 48497] [client 172.XX.XX.XX:57477] PHP Fatal error:  Uncaught TypeError: ldap_count_entries(): Argument #2 ($result) must be of type LDAP\\Result, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php:84\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(84): ldap_count_entries()\n#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(66): search_on_loginnt()\n#2 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(45): verif_pw_ldap()\n#3 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(90): require_once('...')\n#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(321): require_once('...')\n#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')\n#6 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 84, referer: https://inventory.domain.XYZ/index.php
[Tue Aug 23 10:01:08.903930 2022] [php:warn] [pid 48497] [client 172.XX.XX.XX:57484] PHP Warning:  ldap_search(): Search: Bad search filter in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 83, referer: https://inventory.domain.XYZ/index.php
[Tue Aug 23 10:01:08.904051 2022] [php:error] [pid 48497] [client 172.XX.XX.XX:57484] PHP Fatal error:  Uncaught TypeError: ldap_count_entries(): Argument #2 ($result) must be of type LDAP\\Result, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php:84\nStack trace:\n#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(84): ldap_count_entries()\n#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(66): search_on_loginnt()\n#2 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(45): verif_pw_ldap()\n#3 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(90): require_once('...')\n#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(321): require_once('...')\n#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')\n#6 {main}\n  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 84, referer: https://inventory.domain.XYZ/index.php
```

**Comment by Lea9250** [comment]
Hi @MichaIJarosz,

From the logs you sent, it seems like the LDAP filters you are using are not correct (`ldap_search(): Search: Bad search filter`). Documentation is available to help you set these filters : https://wiki.ocsinventory-ng.org/04.Management-console-and-its-advanced-features/Synchronization-between-OCS-and-LDAP/

Regards,
Léa
